  void set_external_caught_exception(bool value) {
    thread_local_top_.external_caught_exception_ = value;
  }